dist: trusty
language: node_js
node_js: lts/*
cache:
  npm: true
stages:
  - name: test-branch
    if: branch NOT IN (master, next)
  - name: test-next
    if: branch = next
  - name: test-master
    if: branch = master
  - name: deploy
    if: branch IN (master, next)
before_script:
  # Configure Git to fetch all branches and fetch master
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
jobs:
  include:
    - stage: test-branch
      script:
        - git fetch origin next
        - npm run format:check
        - npm run affected:lint -- --base=origin/next --parallel || npm run affected:lint -- --all --parallel
        - COVERAGE=true npm run affected:test -- --base=origin/next --parallel || npm run affected:test -- --all --parallel
        - npm run build-non-libs
        - npm run affected:build -- --base=origin/next --parallel || npm run affected:build -- --all --parallel
    - stage: test-next
      script:
        - git fetch origin master
        - npm run format:check
        - npm run affected:lint -- --base=origin/master --parallel || npm run affected:lint -- --all --parallel
        - COVERAGE=true npm run affected:test -- --base=origin/master --parallel || npm run affected:test -- --all --parallel
    - stage: test-master
      script:
        - npm run format:check
        - npm run affected:lint -- --all --parallel
        - COVERAGE=true npm run npm run affected:test -- --all --parallel
    - stage: deploy
      script:
        - npm run build
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote add -f pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git fetch pub $TRAVIS_BRANCH
        - git checkout $TRAVIS_BRANCH
      after_deploy:
        - npx lerna exec -- cat ./dist/package.json
      deploy:
        - provider: script
          script: npm run release
          skip_cleanup: true
          keep_history: true
          on:
            tags: false
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^(master)$'
        - provider: script
          script: npm run release-next
          skip_cleanup: true
          keep_history: true
          on:
            tags: false
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^(next)$'
        - provider: script
          script: npm run release-tag
          skip_cleanup: true
          keep_history: true
          on:
            tags: false
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^(beta)$'
