dist: trusty
language: node_js
node_js: lts/*
cache:
  npm: true
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script:
        - npm run format:check
        - npm run lint
        - COVERAGE=true npm run test:ci
        - npm run build:all || npm run build:all # Double build to ensure dependent libs are built first
    - stage: release
      script:
        - npm run build:all
      deploy:
        provider: script
        script: npm run release
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master)$
    - stage: release
      script:
        - npm run build:all
      deploy:
        provider: script
        script: npm run release:tag
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(next)$
