name: Spryker UI Components CI

on:
  push:
    branches:
      - '(^((?!(master|next|(\d+))$).)*$)' 
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  NODE_VERSION: '18.19.1'
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    name: Format check / Lint code / Unit Tests / Build (test-branch)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format check (master branch)
        if: github.ref == 'refs/heads/master'
        run: npm run format:check

      - name: Format check (next branch)
        if: github.ref == 'refs/heads/next'
        run: |
          git fetch origin master
          npm run format:check -- --base=origin/master

      - name: Format check (other branches)
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/next'
        continue-on-error: true
        run: |
          git fetch origin next
          npm run format:check -- --base=origin/next

      - name: Lint code (master branch)
        if: github.ref == 'refs/heads/master'
        run: |
          npm run affected:lint -- --parallel || npm run affected:lint
          npm run stylelint

      - name: Lint code (next branch)
        if: github.ref == 'refs/heads/next'
        run: |
          git fetch origin master
          npm run affected:lint -- --base=origin/master --parallel || npm run affected:lint -- --parallel
          npm run stylelint

      - name: Lint code (other branches)
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/next'
        run: |
          git fetch origin next
          npm run affected:lint -- --base=origin/next --parallel || npm run affected:lint -- --parallel
          npm run stylelint

      - name: Run tests (master branch)
        if: github.ref == 'refs/heads/master'
        run: |
          COVERAGE=true npm run affected:test -- --parallel || npm run affected:test

      - name: Run tests (next branch)
        if: github.ref == 'refs/heads/next'
        run: |
          git fetch origin master
          COVERAGE=true npm run affected:test -- --base=origin/master --parallel || npm run affected:test -- --parallel

      - name: Run tests (other branches)
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/next'
        run: |
          git fetch origin next
          COVERAGE=true npm run affected:test -- --base=origin/next --parallel || npm run affected:test -- --parallel

      - name: Build non-libs
        run: npm run build-non-libs

      - name: Build affected (master branch)
        if: github.ref == 'refs/heads/master'
        run: |
          npm run affected:build -- --parallel || npm run affected:build

      - name: Build affected (non-master branches)
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/next'
        run: |
          git fetch origin next
          npm run affected:build -- --base=origin/next --parallel || npm run affected:build -- --parallel

      - name: Build affected (next branch)
        if: github.ref == 'refs/heads/next'
        run: |
          git fetch origin master
          npm run affected:build -- --base=origin/master --parallel || npm run affected:build -- --parallel

  deploy:
    name: Trigger Deploy Pipeline
    if: (github.ref == 'refs/heads/next' || github.ref == 'refs/heads/master' || contains(github.ref, 'pull/'))
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          echo "Deploy pipeline would be triggered here"
          # Add your deployment logic here
          # This could be a GitHub Actions workflow dispatch event or other deployment method
